# Generated by ‘nixos-generate-config’
{ config, lib, modulesPath, ... }:
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cc205f37-4be4-4db6-a09f-d6e28bf41690";
      fsType = "ext4";
    };
  boot.initrd.luks.devices."luks-c6f788eb-24a0-4a49-9d54-943fd934c77a".device = "/dev/disk/by-uuid/c6f788eb-24a0-4a49-9d54-943fd934c77a";
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4B1C-B592";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  swapDevices =
    [ { device = "/dev/disk/by-uuid/14b89c1a-8959-46bb-b40d-ca97af157451"; }
    ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
