# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/repos/others/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

## cd alternative
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init zsh)"
fi

## ls alternative
if command -v eza &> /dev/null; then
  alias ls="eza"
fi

## Enable autocomplete
autoload -U compinit
compinit

## Helix default editor
if command -v hx &> /dev/null; then
  export EDITOR=hx
fi
