theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# Pretend the keyboard is QWERTY (which it is not) for normal mode
#   n <-> j
n = "move_line_down"            # j
N = "join_selections"           # J
j = "search_next"               # n
J = "search_prev"               # N
#   e <-> k
e = "move_line_up"              # k
E = "move_line_up"
k = "move_next_word_end"        # e
K = "move_next_long_word_end"   # E

[keys.select]
e = "extend_line_up"            # k
n = "extend_line_down"          # j
j = "extend_search_next"        # n
J = "extend_search_prev"        # N
