theme = "dark_plus"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = false
# idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["position", "diagnostics", "file-encoding", "register", "spinner", "selections"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"C-q" = ":buffer-close"
"C-n" = "extend_search_next"
"C-p" = "extend_search_prev"
"C-j" = ["insert_mode", "insert_newline", "normal_mode"]

[keys.normal.space.space]
b = ":sh echo git blame -L ${linenumber} -- ${filename}"
c = ":open ~/.config/helix/config.toml ~/.config/helix/languages.toml"
r = [":write-all", ":config-reload"]
w = ":toggle-option soft-wrap.enable"
t = ":set-option soft-wrap.wrap-at-text-width true"
f = ":set-option soft-wrap.wrap-at-text-width false"
h = [":vsplit-new", ":pipe (curl --silent https://raw.githubusercontent.com/helix-editor/helix/master/helix-term/src/commands.rs | grep -e '^fn [^(]*([a-z]*: &mut Context)' | sed -E 's%^fn ([^(]*).*%\\1%') | sort"]
