theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"

[editor.soft-wrap]
enable = true

# [editor.lsp]
# display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
n = "extend_search_next"
N = "extend_search_prev"
"A-n" = "search_next"
"A-N" = "search_prev"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal.space.t]
c = [":write-all", ":config-reload"]
w = ":sh pwd"
h = [":vsplit-new", ":pipe (curl --silent https://raw.githubusercontent.com/helix-editor/helix/master/helix-term/src/commands.rs | grep -e '^fn [^(]*([a-z]*: &mut Context)' | sed -E 's%^fn ([^(]*).*%\\1%') | sort"]
