theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space.t]
c = [":write-all", ":config-reload"]
z = [":vsplit-new", ":pipe (curl --silent https://raw.githubusercontent.com/helix-editor/helix/master/helix-term/src/commands.rs | grep -e '^fn [^(]*([a-z]*: &mut Context)' | sed -E 's%^fn ([^(]*).*%\\1%') | sort"]
