theme = "dark_plus"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = false
cursorline = true
color-modes = true
text-width = 88
popup-border = "popup"
# end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "separator", "selections", "diagnostics", "file-encoding", "read-only-indicator", "file-modification-indicator", "register", "position", "spinner"]
right = ["version-control", "spacer", "file-name"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"C-q" = ":buffer-close"
"C-n" = "extend_search_next"
"C-p" = "extend_search_prev"
"C-j" = ["insert_mode", "insert_newline", "normal_mode"]

[keys.normal.space.space]
b = ":sh echo git blame -L ${linenumber} -- ${filename}"
c = ":open ~/.config/helix/config.toml ~/.config/helix/languages.toml"
f = ":set-option soft-wrap.wrap-at-text-width false"
g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
r = [":write-all", ":config-reload"]
t = ":set-option soft-wrap.wrap-at-text-width true"
w = ":toggle-option soft-wrap.enable"
