theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
right = ["position", "diagnostics", "file-encoding", "version-control", "register", "selections"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"C-n" = "extend_search_next"
"C-p" = "extend_search_prev"
"C-j" = ["insert_mode", "insert_newline", "normal_mode"]

[keys.normal.space.t]
c = [":write-all", ":config-reload"]
w = ":sh pwd"
h = [":vsplit-new", ":pipe (curl --silent https://raw.githubusercontent.com/helix-editor/helix/master/helix-term/src/commands.rs | grep -e '^fn [^(]*([a-z]*: &mut Context)' | sed -E 's%^fn ([^(]*).*%\\1%') | sort"]
