theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# Pretend the keyboard is QWERTY (which it is not) for normal mode.
#   n <- j
n = "move_line_down"            # j
k = "search_next"               # n
K = "search_prev"               # N
#   e <- k
e = "move_line_up"              # k
j = "move_next_word_end"        # e
J = "move_next_long_word_end"   # E
