theme = "dark_plus"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = false
cursorline = true
color-modes = true
# idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
"`" = "`"

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "separator", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["position", "diagnostics", "file-encoding", "register", "spinner", "selections"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"C-q" = ":buffer-close"
"C-n" = "extend_search_next"
"C-p" = "extend_search_prev"
"C-j" = ["insert_mode", "insert_newline", "normal_mode"]

[keys.normal.space.space]
b = ":sh echo git blame -L ${linenumber} -- ${filename}"
c = ":open ~/.config/helix/config.toml ~/.config/helix/languages.toml"
f = ":set-option soft-wrap.wrap-at-text-width false"
g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
r = [":write-all", ":config-reload"]
t = ":set-option soft-wrap.wrap-at-text-width true"
w = ":toggle-option soft-wrap.enable"
