# [language-server.codebook]
# command = "codebook-lsp"
# args = ["serve"]

[[language]]
name = "markdown"
# language-servers = ["codebook"]
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.wrap-indicator = ""

[[language]]
name = "python"
language-servers = ["pylsp"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
rope = {enabled = true}  # Completion & renaming
jedi_completion = {enabled = true}  # Autocompletion, static analysis and refactoring
ruff = {enabled = true}  # Linter & code formatter
black = {enabled = false}  # Code formatter
flake8 = {enabled = false}  # Style Guide
pyflakes = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pydocstyle = {enabled = false}  # DocString conformance (PEP 257)
autopep8 = {enabled = false}
yapf = {enabled = false}
pylint = {enabled = false}

[[language]]
name = "nix"
indent = {tab-width = 2, unit = " "}

[[language]]
name = "hcl"

[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve", "-log-file", "/dev/null"]

[[language]]
name = "rust"

[language.inline-diagnostics]
cursor-line = "disable"
