[[language]]
name = "markdown"
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.wrap-indicator = ""

[[language]]
name = "python"
language-servers = ["pylsp"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
black = { enabled = true }  # Code formatter
flake8 = {enabled = true}  # Style Guide
rope = { enabled = true }  # Refactoring
jedi_completion = {enabled = true}  # Autocompletion, static analysis and refactoring
ruff = {enabled = true}  # Linter
pydocstyle = {enabled = false}  # DocString conformance (PEP 257)

[[language]]
name = "nix"
indent = { tab-width = 2, unit = " " }
