# Generated by ‘nixos-generate-config’
{ config, lib, modulesPath, ... }:
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a44f0718-225d-4ca3-b11b-c07cdb2c4f73";
      fsType = "ext4";
    };
  boot.initrd.luks.devices."luks-f945c1aa-b9f5-4fc5-8790-eea07aa5b4a9".device = "/dev/disk/by-uuid/f945c1aa-b9f5-4fc5-8790-eea07aa5b4a9";
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C38E-C8C7";
      fsType = "vfat";
    };
  swapDevices =
    [ { device = "/dev/disk/by-uuid/7e80c72f-91f4-4500-ac0b-32b02b3ab4ae"; }
    ];
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
