# Generated by ‘nixos-generate-config’
{ config, lib, modulesPath, ... }:
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/89500097-39c9-4c36-9442-00aadbef40d8";
      fsType = "ext4";
    };
  boot.initrd.luks.devices."luks-1d7f53ad-e985-4bf7-9a38-44a35161d785".device = "/dev/disk/by-uuid/1d7f53ad-e985-4bf7-9a38-44a35161d785";
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8678-CB48";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  swapDevices =
    [ { device = "/dev/disk/by-uuid/7314b26e-84f8-4a84-9d96-b289deeed178"; }
    ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
